version: '3'

services:
  postgres:
    image: postgres
    ports: [ 5432:5432 ]
    environment:
      POSTGRES_USER: noctf
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: noctf
    volumes:
      - postgres:/var/lib/postgres/data/
  redis:
    image: redis
    ports: [ 6379:6379 ]
  noctf_dev_server:
    image: node
    ports: [ 3000:3000 ]
    command: ["sh", "-c", "yarn workspace @noctf/server run knex migrate:latest && yarn workspace @noctf/server dev:docker"]
    working_dir: /srv/
    environment:
      NODE_ENVIRONMENT: development
      NOCTF_SECRETS_DIR: /data/secrets
      NOCTF_SECRETS_WATCH: "true"
      NOCTF_REDIS_URL: redis://redis:6379/
      NOCTF_DATABASE_CLIENT: postgresql
      NOCTF_DATABASE_CONNECTION_NAME: noctf
      NOCTF_DATABASE_CONNECTION_HOST: postgres
      NOCTF_DATABASE_CONNECTION_USERNAME: noctf
      NOCTF_DATABASE_CONNECTION_PASSWORD: devpassword
    volumes:
      - ./:/srv/
      - ./data:/data:ro

volumes:
  postgres: