services:
  redis:
    image: valkey/valkey:8-alpine
    ports:
      - 6379:6379
  nats:
    image: nats
    command: -js
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
  postgres:
    image: postgres:17-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=noctf
      - POSTGRES_DB=noctf
    ports:
      - 5432:5432
volumes:
  postgres: