services:
  redis:
    image: valkey/valkey:8-alpine
    ports:
      - "6379"

  nats:
    image: nats
    command: -js
    ports:
      - "4222"

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=noctf
      - POSTGRES_DB=noctf
    ports:
      - "5432"
