packages:
  # core libs
  - "core/*"
  # user plugins
  - "plugins/*"
  # deployable applications
  - "apps/*"

catalog:
  "@eslint/js": ^9.17.0
  "@types/node": ^22.7.4
  "@types/pg": ^8.11.10
  "eslint": ^9.17.0
  "typescript": ^5.7.2
  "typescript-eslint": ^8.18.2
  "tsx": ^4.19.1
  "ajv": ^8.17.1
  "esbuild": ^0.24.1
  "kysely": ^0.27.5
  "ky": ^1.7.2
  "pg": ^8.13.1
  "awilix": ^12.0.4
  "fastify": ^5.2.0
  "@fastify/swagger": ^9.3.0
  "pino-pretty": ^13.0.0
  "@sinclair/typebox": ^0.34.13
  "vitest": ^2.1.8
  "nanoid": ^5.0.9
  "p-limit": ^6.2.0
  "@vitest/coverage-v8": ^2.1.8
  "vitest-mock-extended": ^2.0.2
  "openapi-typescript": "^7.5.2"
  "openapi-fetch": "^0.13.4"
  "expr-eval": "npm:expr-eval-fork@^2.0.2"
