packages:
  # core libs
  - 'core/*'
  # user plugins
  - 'plugins/*'
  # deployable applications
  - 'apps/*'

catalog:
  '@eslint/js': ^9.12.0
  '@types/node': ^22.7.4
  '@types/pg': ^8.11.10
  'eslint': ^9.12.0
  'typescript': ^5.6.2
  'typescript-eslint': ^8.8.0
  'tsx': ^4.19.1
  'kysely': ^0.27.4
  'pg': ^8.13.0
  'redis': ^4.7.0
  'awilix': ^12.0.1
  'fastify': ^5.0.0
