services:
  server:
    environment:
      ALLOWED_ORIGINS: "${DEMO_DOMAIN:-demo.noctf.dev},localhost,*.noctf-beta.pages.dev"
      API_URL: "${DEMO_API_BASE_URL:-https://api.demo.noctf.dev}"
      TOKEN_SECRET: "${DEMO_TOKEN_SECRET:?run.sh must generate the token secret}"

  worker:
    environment:
      TOKEN_SECRET: "${DEMO_TOKEN_SECRET:?run.sh must generate the token secret}"

  seeder:
    image: ghcr.io/noctf-project/noctf/server
    command: ["node", "/demo/seed.mjs"]
    depends_on:
      server:
        condition: service_started
    environment:
      DEMO_DOMAIN: "${DEMO_DOMAIN:-demo.noctf.dev}"
      DEMO_ROOT_URL: "${DEMO_ROOT_URL:-https://demo.noctf.dev}"
      DEMO_API_BASE_URL: "${DEMO_API_BASE_URL:-https://api-demo.noctf.dev}"
      DEMO_API_PORT: "${DEMO_API_PORT:-8000}"
      DEMO_LOCAL_API_URL: "http://server:8000"
    volumes:
      - "${DEMO_DIR:?}/seed.mjs:/demo/seed.mjs:ro"

  # since all the containers are running as private, we need to forward out the port
  proxy:
    image: gogost/gost:3
    command:
      - -L
      - tcp://:8000/server:8000
    depends_on:
      server:
        condition: service_started
    ports:
      - "${DEMO_API_PORT:-8000}:8000"
    networks:
      - default
      - public

  web: !reset null

  postgres:
    volumes: !reset []

volumes: !reset {}

networks:
  default:
    internal: true
  public: {}
