name: Build and Push Docker Images

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build images with Docker Compose
      run: |
        docker compose build

    - name: Extract metadata for built images
      id: docker-metadata
      run: |
        BUILT_SERVICES=`yq -o=json -I=0 '([.services[] | select(has("build") and has("image")) | .image] | unique)' docker-compose.yml`

        echo "built_services=$BUILT_SERVICES" >> $GITHUB_OUTPUT
        echo "Built services: $BUILT_SERVICES"

    - name: Output pushed images
      env:
        BUILT_SERVICES: "${{steps.docker-metadata.outputs.built_services}}"
      run: |
        for image in `echo "$BUILT_SERVICES" | jq -cr '.[]'`
        do
          docker push "$image" &
        done
        wait