name: ci-tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: CI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Read Node version
        id: nvm
        run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Install pnpm and deps
        uses: pnpm/setup@v2
        with:
          runtime: node@${{ steps.nvm.outputs.version }}
          cache: true

      - name: Format Check
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Unit Tests
        run: pnpm test:unit

      - name: Integration Tests
        run: pnpm test:integ
