on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  server-test-integ:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
    - uses: actions/checkout@v2
    - name: cache node_modules
      uses: actions/cache@v1
      id: cache-yarn
      with:
        path: node_modules
        key: ${{ runner.os }}-cache-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-cache-yarn-${{ hashFiles('yarn.lock') }}
    - name: yarn install
      if: steps.cache-yarn.outputs.cache-hit != 'true'
      run: yarn install --immutable
    - name: server integ test
      run: yarn workspace noctf-server test:integration
